### ISSUE TITLE
Code samples don't compile

### ISSUE THREAD

**Issue by dmit** [jdegoes/intro-to-ps#2]
Whenever an integer literal is passed to a function expecting `Number` I get a type error.
```
PSCi, version 0.11.4
Type :? for help

> :paste
… n :: Number
… n = 1
…
Error found:
in module $PSCI
at  line 2, column 5 - line 2, column 5

  Could not match type

    Int

  with type

    Number


while checking that type Int
  is at least as general as type Number
while checking that expression 1
  has type Number
in value declaration n

See https://github.com/purescript/documentation/blob/master/errors/TypesDoNotUnify.md for more information,
or to contribute content related to this error.
```
I don't really know PureScript, so not sure if this an error on my part or if the language requires `Number` literals to always specify the fractional part.

**Comment by jdegoes** [comment]
The `Number` needs to be an `Int`. Is this in the comments?

**Comment by dmit** [comment]
Sorry, should have specified - this is in `presentation.md`.
